In [2]:
import numpy as np

In [5]:
a=np.matrix([[1,2],[2,3]])
a

matrix([[1, 2],
        [2, 3]])

In [4]:
a.ndim

2

In [9]:
b=np.matrix([[1,2],[2,3],[4,5]])
b

matrix([[1, 2],
        [2, 3],
        [4, 5]])

In [7]:
b.ndim

2

In [13]:
c=np.matrix([[1,2,3],[2,3,4],[4,5,6]])
c

matrix([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [11]:
c.ndim

2

In [16]:
d=np.array([[[1,2,3],[2,3,4],[4,5,6]]])
d

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [17]:
d.ndim

3

In [36]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [17]:
import pandas as pd
df=pd.read_excel(r'C:\Users\91897\Desktop\pandas.xlsx')
df.head()
df

S.No.        Emp_name  Emp_id  Production  Productive Hours  Productivity
0       1    Vikas Sharma  815864          48              8.00            48
1       2          Sachin  815426          58              6.00            77
2       3           Rohit  812457          12              4.00            24
3       4           Broad  821543          40              7.00            46
4       5       Gilchrist  821546          54              8.00            54
5       6         Symonds  824513          41              7.00            47
6       7         Pollard  875412          42              5.50            61
7       8        Mccullum  822135          60              4.00           120
8       9     Chris Gayle  821546          46              5.00            74
9      10    Morne MorkHD  821354          43              4.67            74
10     11    S Shreesanth  811524          51              4.33            94
11     12       Harbhajan  821546          39              4.00            78
12     13       R.P Singh  812542          35              3.67            76
13     14      Naman Ojha  848571          54              3.33           130
14     15   Manish Pandey  812542          38              3.00           101
15     16  Shikhar Dhawan  812543          56              2.67           168
16     17          Warner  812542          35              4.00            70
17     18         Jacobbs  812546          35              3.67            76

In [29]:
df['Production'].iloc[5]

41

In [27]:
df["Emp_name"].apply(lambda x: x.replace("Mccullum","Brendum Mccullum"))

0                Vikas
1         Sachin Baira
2                Rohit
3                Broad
4            Gilchrist
5              Symonds
6              Pollard
7     Brendum Mccullum
8          Chris Gayle
9         Morne MorkHD
10        S Shreesanth
11           Harbhajan
12           R.P Singh
13          Naman Ojha
14       Manish Pandey
15      Shikhar Dhawan
16              Warner
17             Jacobbs
Name: Emp_name, dtype: object

In [26]:
df['Emp_name']=df['Emp_name'].apply(lambda x: x.replace('Vikas Sharma','Vikas'))

In [23]:
df.head

<bound method NDFrame.head of     S.No.        Emp_name  Emp_id  Production  Productive Hours  Productivity
0       1           Vikas  815864          48              8.00            48
1       2    Sachin Baira  815426          58              6.00            77
2       3           Rohit  812457          12              4.00            24
3       4           Broad  821543          40              7.00            46
4       5       Gilchrist  821546          54              8.00            54
5       6         Symonds  824513          41              7.00            47
6       7         Pollard  875412          42              5.50            61
7       8        Mccullum  822135          60              4.00           120
8       9     Chris Gayle  821546          46              5.00            74
9      10    Morne MorkHD  821354          43              4.67            74
10     11    S Shreesanth  811524          51              4.33            94
11     12       Harbhajan  821546 

In [21]:
df['Emp_name'][1]=("Sachin Baira")

C:\Windows\Temp\ipykernel_14196\2041512075.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Emp_name'][1]=("Sachin Baira")


In [19]:
# How to find memory size of an array?
df.itemsize

AttributeError: 'DataFrame' object has no attribute 'itemsize'

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
ar=np.zeros((5,2))
ar

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
a=np.zeros((10,10))
a.itemsize 

8

In [10]:
a=np.zeros((10,10))
print('%d Bytes'%(a.size*a.itemsize))

800 Bytes


In [12]:
a=np.zeros((10,10))
print('Bytes',a.size*a.itemsize)

Bytes 800


In [14]:
a=np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
# create a null vector of 5thindex is 1.
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [40]:
# Create a vector with values of 10 to 69.

x=np.arange(10,70)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69])

In [48]:
# Reverse a vector

y=np.arange(70,9,-1)
y


array([70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54,
       53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37,
       36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20,
       19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [53]:
y=np.arange(10,70)
y[::-1]


array([69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53,
       52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36,
       35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19,
       18, 17, 16, 15, 14, 13, 12, 11, 10])

In [52]:
f=np.array([1,2,3,4,5])
g=f[::-1]
g

array([5, 4, 3, 2, 1])

In [64]:
# Create a 3*3 matrix with values ranging between 0 to 8

a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
# Create a 3*3 identity matrix?.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
# Create a random vector of size 30 and find the mean value of it?.

z=np.random.random(30).mean()
print(z)

0.5542747902025973


In [74]:
# Create a random vector of size 30 and find the mean value of it?.

z=np.random.random(30)
z.mean()
print(z)

[0.42408046 0.66544176 0.21222651 0.07987374 0.8081162  0.65930859
 0.56419829 0.14056425 0.78869607 0.40797863 0.38933928 0.98934029
 0.59501643 0.49503356 0.27893812 0.35381087 0.05326873 0.67079816
 0.08628627 0.45062788 0.79221595 0.03071588 0.21849227 0.72402509
 0.30739657 0.18668701 0.19944886 0.18569183 0.34455613 0.08068142]


In [84]:
# Create a 2D array with 1 on the border and 0 inside?.
h=np.ones((10,10))
h[1:-1, 1:-1]=0 # here 1:-1 updated twice, one for row and 1 for column.
h

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
# How to add a border(0's) around an existing array?.
h=np.zeros((10,10))
h[1:-1, 1:-1]=1
h


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [95]:
# How to add a border(0's) around an existing array?.
# ANother Way
h=np.ones((10,10))
h=np.pad(h,pad_width=1) # in pad_width we should mention the width how much we want, here we mentioned width as 1
                        # so it updated 0 at border if mention 2 then it will update 0 in 2 rows 
                        # and 2 columns                    
h

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [99]:
h=np.ones((10,10))
h=np.pad(h,pad_width=1,constant_values=2) # here wementioned constant_values as 2 to add in a border 
h                                         # if we are not mentioned any value then bt defaulty considered as 0
         

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [106]:
np.diag(np.ones(4),1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [112]:
# Create a check board 8*8 matrix using the tile function?.
np.tile(np.array([[0,1],[0,1]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [114]:
np.tile(np.array([[0,1],[2,3]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

In [ ]:
# Multiply 5*3 matrix by 3*2 matrix (product)?.


In [ ]:
# Given 1D array , negate all the elements which  are between 3 and 8 in place?.