In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
2. Create a vector with values ranging from 10 to 49.

In [9]:
Vector_range= np.arange(10,50)
print(Vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
matrix_1 = np.arange(9).reshape(3,3)
matrix_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [30]:
import numpy as np
elements = np.array([1,2,0,0,4,0])
print("Original array:")
print(elements)
print("Indices of non-zero elements:")
result = np.where(elements != 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of non-zero elements:
[0 1 4]


In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [40]:
import numpy as np
array1 = np.random.random((10,10))
print("Original Array:")
print(x) 
array1_min, array1_max = array1.min(), array1.max()
print(" ")
print("------------------------------Output------------------------------")
print(" ")
print("Minimum Values:",array1_min)
print("Maximum Values:",array1_max)


Original Array:
[[0.84787029 0.81044258 0.83923347 0.17832891 0.81622242 0.41528982
  0.50582048 0.55665781 0.35775338 0.93755751]
 [0.05904169 0.01552657 0.37196659 0.46104478 0.53913402 0.37785312
  0.71645265 0.64148774 0.80306071 0.65189009]
 [0.00283267 0.28808874 0.50844235 0.79319006 0.42102728 0.16940797
  0.1535553  0.87051001 0.76441676 0.86758285]
 [0.0581878  0.6140362  0.82607114 0.13179912 0.31142393 0.07007146
  0.2006409  0.25029395 0.97356854 0.51130649]
 [0.07825512 0.55776971 0.30572562 0.29181184 0.2658628  0.92121375
  0.7374851  0.64782368 0.39837032 0.74975339]
 [0.62137271 0.97790783 0.39300231 0.53492806 0.59629836 0.14140361
  0.66797257 0.83671047 0.78287164 0.30853251]
 [0.14252443 0.72020983 0.61423613 0.90449091 0.52828273 0.4833714
  0.75233861 0.69753071 0.90046414 0.6955611 ]
 [0.65274361 0.12143877 0.004611   0.29570908 0.10816003 0.95235773
  0.41748582 0.48065469 0.95592107 0.49501684]
 [0.0827935  0.71629485 0.00575388 0.9889744  0.19869192 0.849983

In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [47]:
Random_vector = np.random.random(10)
print("Random Vector is : \n",Random_vector)
print(" ")
Mean_value = Random_vector.mean()
print ("Mean Value of the random vector is :",Mean_value)

Random Vector is : 
 [0.34807221 0.43881587 0.13959047 0.79889534 0.32640029 0.88543503
 0.68823445 0.74336258 0.40899461 0.60253685]
 
Mean Value of the random vector is : 0.5380337712641536
